spring:
  application:
    name: sensitivity-analysis-server

  cloud:
    function:
      definition: consumeRun;consumeCancel;consumeNonEvacuatedEnergyRun;consumeNonEvacuatedEnergyCancel
    stream:
      bindings:
        consumeRun-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sensitivityanalysis.run
          group: sensitivityanalysisGroup
          consumer:
            concurrency: 2
            max-attempts: 1
        publishRun-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sensitivityanalysis.run
        publishResult-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sensitivityanalysis.result
        consumeCancel-in-0:
            destination: ${powsybl-ws.rabbitmq.destination.prefix:}sensitivityanalysis.cancel
        publishCancel-out-0:
            destination: ${powsybl-ws.rabbitmq.destination.prefix:}sensitivityanalysis.cancel
        publishStopped-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sensitivityanalysis.stopped
        publishCancelFailed-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sensitivityanalysis.cancelfailed

        consumeNonEvacuatedEnergyRun-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}nonEvacuatedEnergy.run
          group: sensitivityanalysisGroup
          consumer:
            max-attempts: 1
        publishNonEvacuatedEnergyRun-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}nonEvacuatedEnergy.run
        publishNonEvacuatedEnergyResult-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}nonEvacuatedEnergy.result
        consumeNonEvacuatedEnergyCancel-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}nonEvacuatedEnergy.cancel
        publishNonEvacuatedEnergyCancel-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}nonEvacuatedEnergy.cancel
        publishNonEvacuatedEnergyStopped-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}nonEvacuatedEnergy.stopped
        publishNonEvacuatedEnergyCancelFailed-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}nonEvacuatedEnergy.cancelfailed

      output-bindings: publishRun-out-0;publishResult-out-0;publishCancel-out-0;publishStopped-out-0;publishCancelFailed-out-0;publishNonEvacuatedEnergyRun-out-0;publishNonEvacuatedEnergyResult-out-0;publishNonEvacuatedEnergyCancel-out-0;publishNonEvacuatedEnergyStopped-out-0;publishNonEvacuatedEnergyCancelFailed-out-0
      rabbit:
        bindings:
          consumeRun-in-0:
            consumer:
              auto-bind-dlq: true
              dead-letter-exchange: ${powsybl-ws.rabbitmq.destination.prefix:}sensitivityanalysis.run.dlx
              dead-letter-queue-name: ${powsybl-ws.rabbitmq.destination.prefix:}sensitivityanalysis.run.dlx.dlq
              dead-letter-exchange-type: topic
              quorum:
                enabled: true
                delivery-limit: 2
          consumeNonEvacuatedEnergyRun-in-0:
            consumer:
              auto-bind-dlq: true
              dead-letter-exchange: ${powsybl-ws.rabbitmq.destination.prefix:}nonEvacuatedEnergy.run.dlx
              dead-letter-queue-name: ${powsybl-ws.rabbitmq.destination.prefix:}nonEvacuatedEnergy.run.dlx.dlq
              dead-letter-exchange-type: topic
              quorum:
                enabled: true
                delivery-limit: 2

  jpa:
    properties:
      hibernate:
        order_inserts: true
        jdbc:
          batch_size: 128

powsybl-ws:
  database:
    queryBegin: '&'
    customQuery: ${powsybl-ws.database.customQueryBegin}reWriteBatchedInserts=true
    name: sensitivityanalysis

# default value for loadflow provider "OpenLoadFlow"
sensitivity-analysis:
  default-provider: OpenLoadFlow

non-evacuated-energy:
  default-provider: OpenLoadFlow
