server:
  port: 5030

spring:
  rabbitmq:
    addresses: localhost

powsybl-ws:
  database:
    host: localhost

powsybl:
  services:
    network-store-server:
      base-uri: http://localhost:8080

gridsuite:
  services:
    actions-server:
      base-uri: http://localhost:5022
    filter-server:
      base-uri: http://localhost:5027
    report-server:
      base-uri: http://localhost:5028
    loadflow-server:
      base-uri: http://localhost:5008

management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  endpoints:
    web:
      exposure:
        include: prometheus, health, info