server:
  port: 5030

spring:
  rabbitmq:
    addresses: localhost

powsybl-ws:
  database:
    host: localhost

network-store-server:
  base-uri: http://172.17.0.1:8080

actions-server:
  base-uri: http://172.17.0.1:5022

filter-server:
  base-uri: http://172.17.0.1:5027

report-server:
  base-uri: http://172.17.0.1:5028
